### ISSUE TITLE
application does not start but crashes with an error

### ISSUE THREAD

**Issue by nnako** [Ahmed0tdc/Task-Tracker#1]
Hi Ahmed ;-) ,

just wanted to get started with kivy development and ran into you ToDo-App.

Unfortunately, there seems to be a problem concerning the visibility of the NavigationLayout class. When I do this:

```bash
python main.py
```

I get the following info output:

```bash
[INFO   ] [Logger      ] Record log in ...\.kivy\logs\kivy_21-08-04_1.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "...\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "...\Scripts\python.exe"
[INFO   ] [KivyMD      ] 0.104.2, git-bc7d1f5, 2021-06-06 (installed at "...\lib\site-packages\kivymd\__init__.py")
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 - Build 25.20.100.6793'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) UHD Graphics 620'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 - Build 25.20.100.6793'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
```

and the following error message:

```bash
 Traceback (most recent call last):
   File "main.py", line 211, in <module>
     app.run()
   File "...\lib\site-packages\kivy\app.py", line 949, in run
     self._run_prepare()
   File "...\lib\site-packages\kivy\app.py", line 918, in _run_prepare
     self.load_kv(filename=self.kv_file)
   File "...\lib\site-packages\kivy\app.py", line 691, in load_kv
     root = Builder.load_file(rfilename)
   File "...\lib\site-packages\kivy\lang\builder.py", line 306, in load_file
     return self.load_string(data, **kwargs)
   File "...\lib\site-packages\kivy\lang\builder.py", line 404, in load_string
     widget = Factory.get(parser.root.name)(__no_builder=True)
   File "...\lib\site-packages\kivy\factory.py", line 146, in __getattr__
     raise FactoryException('Unknown class <%s>' % name)
 kivy.factory.FactoryException: Unknown class <NavigationLayout>
```

any suggestions?

Thanks.
Nnako

**Comment by OtmaniCodes** [comment]
Hello there Nnako!

the error you get is due to the `Kivymd` version you have installed on your device, you probably have a version greater than 0.104.1 which is the version I used to build this experiment app more than a year ago (I used python V3.7.4).

_ run the command:  `pip install 'kivymd == 0.104.1'`

_ if that didn't work, check whether or not you have all the required dependencies installed:

![Screenshot 2021-08-09 121106](https://user-images.githubusercontent.com/70540142/128698506-55ca128f-ee34-4216-9faa-f32b5b60f2d1.jpg)

I built this app when I was exploring and learning Kivy development, So I apologize if it has some bugs 😌

**Comment by nnako** [comment]
Hi, ok. thanks for this clarification. reading through all the posts out there, it seems to me that there are loads of problems concerning kivy / kivymd and their different versions... which is a bit discouraging as there seems to be no straight forward way to get to know the concept of this nice kivy thing. ;-(
